python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/hmdb/train --train_target_dataset /data/datasets/hmdb_ucf/ucf/train --val_dataset /data/datasets/hmdb_ucf/ucf/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name hmdb-ucf-head+temporal-barlow-unsup-IBweight=0.01 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.01 --wandb --pretrained_source_model pretrained_source_models/hmdb-ucf-source-head+partial-35xc7vyr-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/hmdb/train --train_target_dataset /data/datasets/hmdb_ucf/ucf/train --val_dataset /data/datasets/hmdb_ucf/ucf/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name hmdb-ucf-head+temporal-barlow-unsup-IBweight=0.05 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.05 --wandb --pretrained_source_model pretrained_source_models/hmdb-ucf-source-head+partial-35xc7vyr-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/hmdb/train --train_target_dataset /data/datasets/hmdb_ucf/ucf/train --val_dataset /data/datasets/hmdb_ucf/ucf/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name hmdb-ucf-head+temporal-barlow-unsup-IBweight=0.1 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.1 --wandb --pretrained_source_model pretrained_source_models/hmdb-ucf-source-head+partial-35xc7vyr-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/ucf/train --train_target_dataset /data/datasets/hmdb_ucf/hmdb/train --val_dataset /data/datasets/hmdb_ucf/hmdb/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name ucf-hmdb-head+temporal-barlow-unsup-IBweight=0.0001 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.0001 --wandb --pretrained_source_model pretrained_source_models/ucf-hmdb-source-head+partial-343fe6qo-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/ucf/train --train_target_dataset /data/datasets/hmdb_ucf/hmdb/train --val_dataset /data/datasets/hmdb_ucf/hmdb/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name ucf-hmdb-head+temporal-barlow-unsup-IBweight=0.0005 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.0005 --wandb --pretrained_source_model pretrained_source_models/ucf-hmdb-source-head+partial-343fe6qo-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/ucf/train --train_target_dataset /data/datasets/hmdb_ucf/hmdb/train --val_dataset /data/datasets/hmdb_ucf/hmdb/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name ucf-hmdb-head+temporal-barlow-unsup-IBweight=0.001 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.001 --wandb --pretrained_source_model pretrained_source_models/ucf-hmdb-source-head+partial-343fe6qo-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/ucf/train --train_target_dataset /data/datasets/hmdb_ucf/hmdb/train --val_dataset /data/datasets/hmdb_ucf/hmdb/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name ucf-hmdb-head+temporal-barlow-unsup-IBweight=0.005 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.005 --wandb --pretrained_source_model pretrained_source_models/ucf-hmdb-source-head+partial-343fe6qo-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/ucf/train --train_target_dataset /data/datasets/hmdb_ucf/hmdb/train --val_dataset /data/datasets/hmdb_ucf/hmdb/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name ucf-hmdb-head+temporal-barlow-unsup-IBweight=0.01 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.01 --wandb --pretrained_source_model pretrained_source_models/ucf-hmdb-source-head+partial-343fe6qo-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/ucf/train --train_target_dataset /data/datasets/hmdb_ucf/hmdb/train --val_dataset /data/datasets/hmdb_ucf/hmdb/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name ucf-hmdb-head+temporal-barlow-unsup-IBweight=0.05 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.05 --wandb --pretrained_source_model pretrained_source_models/ucf-hmdb-source-head+partial-343fe6qo-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/hmdb_ucf/ucf/train --train_target_dataset /data/datasets/hmdb_ucf/hmdb/train --val_dataset /data/datasets/hmdb_ucf/hmdb/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 4 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name ucf-hmdb-head+temporal-barlow-unsup-IBweight=0.1 --project bmvc-2021-ablation --da ib --pseudo_labels --use_queue --queue_size 1024 --ib_loss_weight 0.1 --wandb --pretrained_source_model pretrained_source_models/ucf-hmdb-source-head+partial-343fe6qo-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/kinetics_datasets/kinetics_nec_balanced --train_target_dataset /data/datasets/nec-drone/cropped/train_balanced --val_dataset /data/datasets/nec-drone/cropped/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --accumulate_grad_batches 1 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 3 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name kinetics-nec-head+temporal-barlow-unsup-IBweight=0.0005 --project bmvc-2021-ablation --da ib --use_queue --queue_size 2048 --pseudo_labels --ib_loss_weight 0.0005 --wandb --save_model --pretrained_source_model pretrained_source_models/kinetics-nec-source-head+partial-191p572e-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/kinetics_datasets/kinetics_nec_balanced --train_target_dataset /data/datasets/nec-drone/cropped/train_balanced --val_dataset /data/datasets/nec-drone/cropped/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --accumulate_grad_batches 1 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 3 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name kinetics-nec-head+temporal-barlow-unsup-IBweight=0.001 --project bmvc-2021-ablation --da ib --use_queue --queue_size 2048 --pseudo_labels --ib_loss_weight 0.001 --wandb --save_model --pretrained_source_model pretrained_source_models/kinetics-nec-source-head+partial-191p572e-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/kinetics_datasets/kinetics_nec_balanced --train_target_dataset /data/datasets/nec-drone/cropped/train_balanced --val_dataset /data/datasets/nec-drone/cropped/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --accumulate_grad_batches 1 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 3 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name kinetics-nec-head+temporal-barlow-unsup-IBweight=0.005 --project bmvc-2021-ablation --da ib --use_queue --queue_size 2048 --pseudo_labels --ib_loss_weight 0.005 --wandb --save_model --pretrained_source_model pretrained_source_models/kinetics-nec-source-head+partial-191p572e-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/kinetics_datasets/kinetics_nec_balanced --train_target_dataset /data/datasets/nec-drone/cropped/train_balanced --val_dataset /data/datasets/nec-drone/cropped/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --accumulate_grad_batches 1 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 3 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name kinetics-nec-head+temporal-barlow-unsup-IBweight=0.01 --project bmvc-2021-ablation --da ib --use_queue --queue_size 2048 --pseudo_labels --ib_loss_weight 0.01 --wandb --save_model --pretrained_source_model pretrained_source_models/kinetics-nec-source-head+partial-191p572e-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/kinetics_datasets/kinetics_nec_balanced --train_target_dataset /data/datasets/nec-drone/cropped/train_balanced --val_dataset /data/datasets/nec-drone/cropped/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --accumulate_grad_batches 1 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 3 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name kinetics-nec-head+temporal-barlow-unsup-IBweight=0.025 --project bmvc-2021-ablation --da ib --use_queue --queue_size 2048 --pseudo_labels --ib_loss_weight 0.025 --wandb --save_model --pretrained_source_model pretrained_source_models/kinetics-nec-source-head+partial-191p572e-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/kinetics_datasets/kinetics_nec_balanced --train_target_dataset /data/datasets/nec-drone/cropped/train_balanced --val_dataset /data/datasets/nec-drone/cropped/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --accumulate_grad_batches 1 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 3 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name kinetics-nec-head+temporal-barlow-unsup-IBweight=0.05 --project bmvc-2021-ablation --da ib --use_queue --queue_size 2048 --pseudo_labels --ib_loss_weight 0.05 --wandb --save_model --pretrained_source_model pretrained_source_models/kinetics-nec-source-head+partial-191p572e-ep=19.ckpt

python3 ../main.py --train_source_dataset /data/datasets/kinetics_datasets/kinetics_nec_balanced --train_target_dataset /data/datasets/nec-drone/cropped/train_balanced --val_dataset /data/datasets/nec-drone/cropped/test --epochs 20 --optimizer sgd --lr 0.005 --weight_decay 1e-9 --scheduler cosine --batch_size 32 --accumulate_grad_batches 1 --n_clips 1 --n_frames 16 --frame_size 224 --num_workers 3 --gpus 0 1 --train head+temporal --mlp_hidden_dim 2048 --mlp_n_layers 0 --replace_with_mlp --name kinetics-nec-head+temporal-barlow-unsup-IBweight=0.1 --project bmvc-2021-ablation --da ib --use_queue --queue_size 2048 --pseudo_labels --ib_loss_weight 0.1 --wandb --save_model --pretrained_source_model pretrained_source_models/kinetics-nec-source-head+partial-191p572e-ep=19.ckpt
